# Generated by Django 4.2.1 on 2023-05-31 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_district_division_namef_division_state_namef_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="disrict",),
        migrations.AddField(
            model_name="report",
            name="district",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.district",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="division_namef",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.division",
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="division_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="division",
            name="state_namef",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.state",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="alaqa",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="division",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.division",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="haftawar_ijtima_main_raat_guzarne_wale_Shuraqa",
            field=models.BigIntegerField(default=0, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="islaheaamal_ijtima_maqam",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="islaheaamal_ijtima_shuraqa",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="mehboob_e_attar",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="region",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.region",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sehri_ijtima_maqam",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="sehri_ijtima_shuraqa",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="state",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.state",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="tahajjud_ijtima_maqam",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="tahajjud_ijtima_shuraqa",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="taqseem",
            field=models.BigIntegerField(default=0, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="wusool",
            field=models.BigIntegerField(default=0, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="yaumequfle_madinah",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="zimmedar",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="zimmedar_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="zimmedari",
            field=models.CharField(
                choices=[
                    ("Alaqa Zimmedar Naik Aamal", "Alaqa Zimmedar Naik Aamal"),
                    ("District Zimmedar Naik Aamal", "District Zimmedar Naik Aamal"),
                    ("Division Zimmedar Naik Aamal", "Division Zimmedar Naik Aamal"),
                    ("State Zimmedar Naik Aamal", "State Zimmedar Naik Aamal"),
                    ("Region Zimmedar Naik Aamal", "Region Zimmedar Naik Aamal"),
                    ("Hind Zimmedar Naik Aamal", "Hind Zimmedar Naik Aamal"),
                    ("Other Zimmedar", "Other Zimmedar"),
                ],
                default="madinah",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="region_namef",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.region",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="state_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="alaqa",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="district",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.district",
            ),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="division",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.division",
            ),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="name",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="region",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.region",
            ),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="state",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.state",
            ),
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="zehliHalqa",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
