# Generated by Django 4.2.1 on 2023-06-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_report_disrict_report_district_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="yaumequfle_madinah",
            new_name="yaumequfle_madinah_maqam",
        ),
        migrations.AddField(
            model_name="report",
            name="haftawar_ijtima_main_raat_guzarne_wale_maqam",
            field=models.BigIntegerField(default=0, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="yaumequfle_madinah_shuraqa",
            field=models.BigIntegerField(default=0, max_length=10000, null=True),
        ),
    ]
